// Each question: { text, options: [4 strings], answerIndex: 0-3 }
export const IQ_QUESTIONS = [
  { text: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], answerIndex: 2 },
  { text: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answerIndex: 1 },
  { text: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answerIndex: 3 },
  { text: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'], answerIndex: 1 },
  { text: 'What is the chemical symbol for gold?', options: ['Ag', 'Au', 'Gd', 'Go'], answerIndex: 1 },
  { text: 'How many continents are there?', options: ['5', '6', '7', '8'], answerIndex: 2 },
  { text: 'What is the smallest prime number?', options: ['0', '1', '2', '3'], answerIndex: 2 },
  { text: 'Which country is home to the kangaroo?', options: ['South Africa', 'Australia', 'Brazil', 'India'], answerIndex: 1 },
  { text: 'What is the tallest mountain in the world?', options: ['K2', 'Kilimanjaro', 'Everest', 'Denali'], answerIndex: 2 },
  { text: 'How many legs does a spider have?', options: ['6', '8', '10', '12'], answerIndex: 1 },
  { text: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], answerIndex: 2 },
  { text: 'Which organ pumps blood through the human body?', options: ['Liver', 'Lungs', 'Heart', 'Kidney'], answerIndex: 2 },
  { text: 'What gas do plants primarily absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answerIndex: 2 },
  { text: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], answerIndex: 2 },
  { text: 'What is the largest mammal in the world?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Polar bear'], answerIndex: 1 },
  { text: 'In which year did World War II end?', options: ['1943', '1945', '1947', '1950'], answerIndex: 1 },
  { text: 'What is the freezing point of water in Celsius?', options: ['-10°C', '0°C', '10°C', '32°C'], answerIndex: 1 },
  { text: 'Which country has the largest population in the world?', options: ['India', 'United States', 'China', 'Indonesia'], answerIndex: 0 },
  { text: 'What is the main language spoken in Brazil?', options: ['Spanish', 'Portuguese', 'French', 'Italian'], answerIndex: 1 },
  { text: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], answerIndex: 1 },
  { text: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'], answerIndex: 2 },
  { text: 'Which planet has the most moons?', options: ['Earth', 'Mars', 'Saturn', 'Neptune'], answerIndex: 2 },
  { text: 'Who is known as the father of modern physics?', options: ['Isaac Newton', 'Albert Einstein', 'Nikola Tesla', 'Galileo Galilei'], answerIndex: 1 },
  { text: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answerIndex: 1 },
  { text: 'Which sport is known as "the beautiful game"?', options: ['Basketball', 'Tennis', 'Football (Soccer)', 'Cricket'], answerIndex: 2 },
  { text: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], answerIndex: 2 },
  { text: 'How many colors are there in a rainbow?', options: ['5', '6', '7', '8'], answerIndex: 2 },
  { text: 'What is the capital of Japan?', options: ['Seoul', 'Beijing', 'Tokyo', 'Bangkok'], answerIndex: 2 },
  { text: 'Which instrument has 88 keys?', options: ['Guitar', 'Piano', 'Violin', 'Harp'], answerIndex: 1 },
  { text: 'What is the study of living organisms called?', options: ['Geology', 'Biology', 'Chemistry', 'Astronomy'], answerIndex: 1 },
  { text: 'Which gas makes up most of Earth\'s atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answerIndex: 2 },
  { text: 'Who developed the theory of evolution by natural selection?', options: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Isaac Newton'], answerIndex: 1 },
  { text: 'What is the national sport of Japan?', options: ['Judo', 'Karate', 'Sumo wrestling', 'Kendo'], answerIndex: 2 },
  { text: 'How many bones are in the adult human body?', options: ['186', '206', '226', '246'], answerIndex: 1 },
  { text: 'What is the largest desert in the world?', options: ['Sahara', 'Gobi', 'Antarctic', 'Arabian'], answerIndex: 2 },
  { text: 'Which country invented paper?', options: ['Egypt', 'China', 'Greece', 'India'], answerIndex: 1 },
  { text: 'What does "www" stand for?', options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'], answerIndex: 0 },
  { text: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], answerIndex: 2 },
  { text: 'What is the tallest animal in the world?', options: ['Elephant', 'Giraffe', 'Camel', 'Horse'], answerIndex: 1 },
  { text: 'Who is credited with inventing the telephone?', options: ['Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi'], answerIndex: 2 },
  { text: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answerIndex: 2 },
  { text: 'How many players are on a standard soccer team on the field?', options: ['9', '10', '11', '12'], answerIndex: 2 },
  { text: 'What is the boiling point of water in Celsius at sea level?', options: ['90°C', '100°C', '110°C', '120°C'], answerIndex: 1 },
  { text: 'Which element has the atomic number 1?', options: ['Helium', 'Hydrogen', 'Oxygen', 'Carbon'], answerIndex: 1 },
  { text: 'What is the largest country in the world by land area?', options: ['China', 'United States', 'Canada', 'Russia'], answerIndex: 3 },
];
