export const TRUTHS = [
  'What cartoon character are you most like and why?',
  'If you could only eat one food for the rest of your life, what would it be?',
  'What is the weirdest dream you can remember having?',
  'If you were an animal, what animal would you be?',
  "What's the silliest thing you've ever been scared of?",
  'If you could swap lives with any fictional character for a day, who would it be?',
  'What is the strangest hidden talent you have?',
  'If you could rename yourself, what name would you pick?',
  'What song do you secretly love but are slightly embarrassed to admit?',
  'If you had a theme song that played every time you entered a room, what would it be?',
  "What's the weirdest food combination you secretly enjoy?",
  'If you could only speak in quotes from one movie all day, which movie would you choose?',
  'What imaginary pet would you want if anything were possible?',
  'What superpower would you want, but only for completely silly everyday tasks?',
  'If your pet could talk, what is the first thing they would say about you?',
  'What is the funniest word you know in any language?',
  'If you could be invisible for exactly one hour, what harmless prank would you pull?',
  'What is the most ridiculous outfit you have ever worn?',
  'If you were a flavor of ice cream, what flavor would you be?',
  'What fictional world would you most want to actually live in?',
  'What is the weirdest thing you have searched online this week?',
  'If you could add one rule to every board game ever, what would your rule be?',
  'What is your most completely useless skill?',
  'Describe your personality using only three emoji — which three would you pick?',
  'If you had to wear the same costume every single day for a year, what costume would you pick?',
  'What is the strangest thing you collect or have ever collected?',
  'If animals could vote in an election, which animal would make the best president?',
  'What would your villain origin story be?',
  'If you could have a conversation with any historical inventor, who would it be and what would you ask?',
  'What made-up word would you add to the dictionary and what does it mean?',
];

export const DARES = [
  'Do your best robot dance for 15 seconds.',
  'Speak in a funny accent of your choice for the next two turns.',
  'Do 10 jumping jacks while counting out loud in a silly voice.',
  "Try to lick your elbow for 10 seconds — most people can't do it!",
  'Make your best impression of a T-Rex for 10 seconds.',
  'Sing the chorus of any song in full opera-singer style.',
  'Do your best moonwalk across the room.',
  'Hold a plank position for 20 seconds.',
  'Make three different animal sounds in a row as convincingly as possible.',
  'Do your best slow-motion run across the room and back.',
  "Pretend you are a news anchor and give a 30-second breaking news report on what happened in this room today.",
  'Do your best impression of a melting snowman.',
  'Balance a small object on your head for 15 seconds without touching it.',
  'Narrate the next 30 seconds of your life as if you are in a nature documentary.',
  'Attempt to do the worm — best effort counts!',
  'Make up a 10-second jingle about your favorite food right now.',
  'Do your best impression of someone in the room — keep it kind and fun!',
  'Spell your full name in the air using only your elbow.',
  'Stand perfectly still like a statue for 20 seconds while everyone tries to make you laugh.',
  'Do 5 burpees.',
  'Talk in slow motion for your next two turns — every single word.',
  'Strike three superhero poses and hold each for a full 3 seconds.',
  'Pretend to conduct an invisible orchestra dramatically for 20 seconds.',
  'Use only gestures and no words to describe your favorite movie until someone guesses it.',
  'Roar like a lion three times, each one louder than the last.',
  'Do your best chicken impression for 15 seconds, including sound effects.',
  'Walk like a crab sideways across the room and back.',
  'Do 10 hops on one foot without losing balance — switch feet at 5.',
  'Pretend you are a game show host and give every player an over-the-top grand introduction.',
  'Do your best impression of a robot that is running out of battery.',
];
